server:
  port: 6001
spring:
  application:
    name: cloud-seata-consumer-order
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin://127.0.0.1/orcl
    username: wateruser
    password: tiger
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    alibaba:
      seata:
        tx-service-group: storage-service-group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848